plugins:
  shop_enabled: { client: true, default: true }
  shop_test_mode: { client: true, default: true }
  shop_wechat_mchid: { default: "" }
  shop_wechat_serial_no: { default: "" }
  shop_wechat_api_v3_key: { default: "", secret: true }
  shop_wechat_private_key_pem: { default: "", secret: true }
  shop_wechat_appid: { default: "" }
  shop_wechat_notify_url: { default: "" }
  shop_wechat_oauth_appid: { default: "" }
  shop_wechat_oauth_secret: { default: "" }
  shop_wechat_h5_domain: { default: "" }
  shop_kd100_key: { default: "" }
  shop_kd100_customer: { default: "" }
  shop_kd100_callback_url: { default: "" }
